In [1]:
#Question-1
# Write a NumPy program to replace the negative values in a NumPy array with 0.

In [2]:
import numpy as np
# Creating a numpy array with negative values
arr = np.array([-1, 2, -3, 4, -5])
# Replacing negative values with 0
arr[arr < 0] = 0
print(arr)

[0 2 0 4 0]


In [3]:
#Question-2
# Write a NumPy program to replace all elements of a NumPy array that are greater than the specified array.
# [Expected Output:
# Original array:
# [[ 0.42436315 0.48558583 0.32924763]
# [ 0.7439979 0.58220701 0.38213418]
# [ 0.5097581 0.34528799 0.1563123 ]]
# Replace all elements of the said array with .5 which are greater than. 5
# [[ 0.42436315 0.48558583 0.32924763]
# [ 0.5 0.5 0.38213418]
# [ 0.5 0.34528799 0.1563123 ]]]

In [4]:
import numpy as np
# Creating a numpy array with some values
arr = np.array([[0.42436315, 0.48558583, 0.32924763],
                [0.7439979, 0.58220701, 0.38213418],
                [0.5097581, 0.34528799, 0.1563123]])
# Replacing all elements of the array that are greater than 0.5 with 0.5
arr[arr > 0.5] = 0.5
print(arr)

[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [ ]:
#Question-3
# Write a NumPy program to convert a NumPy array into Python list structure.

In [5]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a)

[10 20 30 40 50]


In [ ]:
#Question-4
# Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [8]:
import numpy as np
# Creating a NumPy array with numbers from 0 to 10 (inclusive)
arr = np.arange(11)
# Shuffling the array
np.random.shuffle(arr)
print(arr)

[ 9  0  8  4  6  7  3  2 10  5  1]


In [ ]:
#Question-5
# Write a NumPy program to convert 1-D arrays as columns into a 2-D array.Sample array: (10,20,30), (40,50,60)

In [11]:
import numpy as np
# Creating 1-D arrays
arr1 = np.array([10, 20, 30])
arr2 = np.array([40, 50, 60])
# Creating a 2-D array from the 1-D arrays
arr_2d = np.column_stack((arr1, arr2))
print(arr_2d)

[[10 40]
 [20 50]
 [30 60]]


In [ ]:
#Question-6
# Write a NumPy program to concatenate two 2-dimensional arrays.
# Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]

In [12]:
import numpy as np
# Creating the two 2-D arrays
arr1 = np.array([[0, 1, 3], [5, 7, 9]])
arr2 = np.array([[0, 2, 4], [6, 8, 10]])
# Concatenating the two 2-D arrays along the rows (axis=0)
arr_concat = np.concatenate((arr1, arr2), axis=0)
print(arr_concat)

[[ 0  1  3]
 [ 5  7  9]
 [ 0  2  4]
 [ 6  8 10]]


In [ ]:
#Question-7
# Write a NumPy program to create a 3x3 identity matrix

In [15]:
import numpy as np
# Creating a 3x3 identity matrix
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Question-8
# Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [17]:
import numpy as np
# Creating an array of 10 zeros
zeros_array = np.zeros(10)
# Creating an array of 10 ones
ones_array = np.ones(10)
# Creating an array of 10 fives
fives_array = np.ones(10) * 5
# Concatenating the arrays horizontally
result = np.concatenate([zeros_array, ones_array, fives_array])
print(result)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


In [18]:
#Question-9
# Write a NumPy program to get help on the add function.

In [19]:
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
b=np.array([[1,2,3],[4,5,6]])
c=np.add(a,b)
print(c)

[[11 22 33]
 [44 55 66]]


In [ ]:
#Question-10
# Write a NumPy program to create a 5x5 matrix with row values ranging from 0 to 4.

In [21]:
import numpy as np
# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.zeros((5, 5))
for i in range(5):
    matrix[i] = i
# Print the resulting matrix
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [ ]:
#Question-11
# Write a NumPy program to move axes of an array to new positions. Other axes remain in their original order.
# Expected Output:
# (3, 4, 2)
# (4, 2, 3)

In [22]:
import numpy as np
# Create a sample array
arr = np.random.randint(10, size=(3, 4, 2))
# Move the second axis to the first position, and the first axis to the last position
new_arr = np.moveaxis(arr, (1, 0), (-1, 0))
# Print the shapes of the original and new arrays
print(arr.shape)
print(new_arr.shape)

(3, 4, 2)
(3, 2, 4)


In [23]:
#Question-12
# Write a NumPy program to view inputs as arrays with at least two dimensions, three dimensions.

In [24]:
import numpy as np
# Define a 1-dimensional array
arr1d = np.array([1, 2, 3, 4, 5])
# View the array as a 2-dimensional array
arr2d = np.atleast_2d(arr1d)
# View the array as a 3-dimensional array
arr3d = np.atleast_3d(arr1d)
# Print the shapes of the arrays
print(arr1d.shape)
print(arr2d.shape)
print(arr3d.shape)

(5,)
(1, 5)
(1, 5, 1)


In [ ]:
#Question-13
# Write a NumPy program to create a 4x4 array, now create a new array from the said array swapping first and last, 
# second and third columns.

In [25]:
import numpy as np
# create a 4x4 array
arr = np.arange(1, 17).reshape(4, 4)
print("Original array:")
print(arr)
# create a new array from the original array swapping columns
new_arr = arr[:, [3, 1, 2, 0]]
print("New array after swapping columns:")
print(new_arr)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
New array after swapping columns:
[[ 4  2  3  1]
 [ 8  6  7  5]
 [12 10 11  9]
 [16 14 15 13]]


In [26]:
#Question-14
# Write a NumPy program to multiply two given arrays of the same size element-by-element.

In [27]:
import numpy as np
# Create two arrays of the same size
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
# Multiply the arrays element-by-element
result = arr1 * arr2
# Print the result
print(result)

[ 4 10 18]


In [28]:
#Question-15
# Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.

In [29]:
import numpy as np
# create a 4x4 array of zeros
arr = np.zeros((4, 4), dtype=int)
# fill the array with the staggered pattern
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
# print the resulting array
print(arr)

[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]
