# Covariance - Programming Assignment.

In [1]:
#Question-1
# create a two numpy arrays and find the variance between two of them

In [8]:
import numpy as np
x=np.array([0,1,2])
y=np.array([2,1,0])
print('covariance matrix is \n',np.cov(x,y))

covariance matrix is 
 [[ 1. -1.]
 [-1.  1.]]


In [2]:
#Question-2
# find the covariance of a given array
# x=np.array([[3,1,4],[7,3,8],[1,5,7]])

In [9]:
import numpy as np
x=np.array([[3,1,4],[7,3,8],[1,5,7]])
print('covariance matrix is \n',np.cov(x))

covariance matrix is 
 [[2.33333333 4.         0.66666667]
 [4.         7.         0.        ]
 [0.66666667 0.         9.33333333]]


In [3]:
#Question-3
# Find the covariance of two series, define two list and covert to series then find the covariance

In [11]:
import pandas as pd
a=[2,3,2.7,3.2,4.1]
b=[10,14,12,15,20]
x=pd.Series(a)
y=pd.Series(b)
print('covariance of two series is:',x.cov(y))

covariance of two series is: 2.849999999999999


In [13]:
#Question-4
# Find the covariance from the given Dataframe:
# data={'col1':[1,5,4],'col2':[3,7,1],'col3':[6,8,1],'col4':[10,7,2]}

In [15]:
import pandas as pd
data={'col1':[1,5,4],'col2':[3,7,1],'col3':[6,8,1],'col4':[10,7,2]}
df=pd.DataFrame(data)
print(df.cov())

          col1       col2  col3       col4
col1  4.333333   2.666667   0.0  -5.166667
col2  2.666667   9.333333  10.0   5.666667
col3  0.000000  10.000000  13.0  11.500000
col4 -5.166667   5.666667  11.5  16.333333


In [5]:
#Question-5
# Create a dataframe with Nan values and find their covariance

In [16]:
import pandas as pd
import numpy as np
data={'col1':[1,5,np.nan],'col2':[3,np.nan,1],'col3':[6,8,1],'col4':[10,7,np.nan]}
df=pd.DataFrame(data)
print(df.cov())

      col1  col2  col3  col4
col1   8.0   NaN   4.0  -6.0
col2   NaN   2.0   5.0   NaN
col3   4.0   5.0  13.0  -3.0
col4  -6.0   NaN  -3.0   4.5


# Perason's and Spearman Correlation -Programming Assignment

In [17]:
#Question-1
# find the pearson's and spearman Correlation of given below data using numpy
# x=[48,67,89,76,55,66,89,90,99,100,100,32,55]
# y=[52,61,78,81,50,49,95,100,100,90,89,21,62]

In [13]:
import numpy as np
x=[48,67,89,76,55,66,89,90,99,100,100,32,55]
y=[52,61,78,81,50,49,95,100,100,90,89,21,62]
print('pearsons correlation is \n',np.corrcoef(x,y))
print()
print('spearman correlation is \n',np.corrcoef(x,y))

pearsons correlation is 
 [[1.         0.93195306]
 [0.93195306 1.        ]]

spearman correlation is 
 [[1.         0.93195306]
 [0.93195306 1.        ]]


In [18]:
#Question-2
# find the pearson's and spearman correlation of given below data using scipy
# x=[48,67,89,76,55,66,89,90,99,100,100,32,55]
# y=[52,61,78,81,50,49,95,100,100,90,89,21,62]

In [53]:
import pandas as pd
from scipy.stats import pearsonr,spearmanr
x=[48,67,89,76,55,66,89,90,99,100,100,32,55]
y=[52,61,78,81,50,49,95,100,100,90,89,21,62]
print('Pearsons coefficient is:',pearsonr(x,y))
print('Spearman coefficient is:',spearmanr(x,y))

Pearsons coefficient is: (0.9319530597064699, 3.5520847631734183e-06)
Spearman coefficient is: SpearmanrResult(correlation=0.842544651209741, pvalue=0.0002999969301816804)


In [66]:
#Question-3
# Calculate the correlation coefficient by Pearson's correlation coefficient, calculate values of x^2,y^2 ,xy
# and display them in a series:
# x=21,31,25,40,47,38
# y=70,55,60,78,66,80

In [3]:
import math
X = [21, 31, 25, 40, 47, 38]
Y = [70, 55, 60, 78, 66, 80]
n = len(X)
mean_X = sum(X) / n
mean_Y = sum(Y) / n
std_X = math.sqrt(sum([(x - mean_X)**2 for x in X]) / (n - 1))
std_Y = math.sqrt(sum([(y - mean_Y)**2 for y in Y]) / (n - 1))
cov = sum([(X[i] - mean_X) * (Y[i] - mean_Y) for i in range(n)]) / (n - 1)
corr = cov / (std_X * std_Y)
# Calculate x^2, y^2, and xy
X_squared = [x**2 for x in X]
Y_squared = [y**2 for y in Y]
XY = [X[i] * Y[i] for i in range(n)]
print("Pearson's correlation coefficient: {:.3f}".format(corr))
print("Values of X^2: ", X_squared)
print("Values of Y^2: ", Y_squared)
print("Values of XY: ", XY)


Pearson's correlation coefficient: 0.347
Values of X^2:  [441, 961, 625, 1600, 2209, 1444]
Values of Y^2:  [4900, 3025, 3600, 6084, 4356, 6400]
Values of XY:  [1470, 1705, 1500, 3120, 3102, 3040]


In [ ]:
#Question-4
# Write a program to find spearman's coefficient from given values:
# x=[15,18,21,15,21]
# y=[25,25,27,27,27]

In [8]:
from scipy.stats import spearmanr
x=[15,18,21,15,21]
y=[25,25,27,27,27]
print('spearmans coefficient is:',spearmanr(x,y))

spearmans coefficient is: SpearmanrResult(correlation=0.45643546458763845, pvalue=0.4397101096353205)


In [21]:
#Question-5
# The scores for nine students in physics and maths are as follows find the spearmans coefficient;
# Physics: 35,23,47,17,10,43,9,6,28
# Mathematics: 30,33,45,23,8,49,12,4,31

In [55]:
from scipy.stats import spearmanr
Physics=[35,23,47,17,10,43,9,6,28]
Mathematics=[30,33,45,23,8,49,12,4,31]
print('Physics and Mathematics of Sperarmans Coefficient:',spearmanr(Physics,Mathematics))

Physics and Mathematics of Sperarmans Coefficient: SpearmanrResult(correlation=0.9, pvalue=0.0009430623223403293)


In [10]:
from scipy.stats import spearmanr

physics_scores = [35, 23, 47, 17, 10, 43, 9, 6, 28]
math_scores = [30, 33, 45, 23, 8, 49, 12, 4, 31]

rho, _ = spearmanr(physics_scores, math_scores)

print("Spearman's rank correlation coefficient: {:.3f}".format(rho))


Spearman's rank correlation coefficient: 0.900


# Population and Sample -Programming Assignment.

In [ ]:
#Question-1
# Random sampling using weights, write a program that creates a random sample from a population using weighted probabilities.
# Definition: In weighted random sampling (WRS) the items are weighted and the probability of each item to be
#             selected is determined by its relative weight.
# import pandas as pds
# TimeToReach vs distance
# time2reach =  {"Distance":[10,15,20,25,30,35,40,45,50,55],
#                "TimeToReach":[15,20,25,30,40,45,50,60,65,70]};

# dataFrame = pds.DataFrame(data=time2reach);

# weight define
# w = pds.Series(data=[0.05, 0.05, 0.05,0.05, 0.05, 0.1,0.15, 0.15, 0.15,0.2]);

In [29]:
import random as rd
import pandas as pd
time2reach={'Distance':[10,15,20,25,30,35,40,45,50,55],
            'TimeToReach':[15,20,25,30,40,45,50,60,65,70]}
dataframe=pd.DataFrame(data=time2reach)
w = pd.Series(data=[0.05, 0.05, 0.05,0.05, 0.05, 0.1,0.15, 0.15, 0.15,0.2])
sample=dataframe.sample(n=2,random_state=1)
print(sample)
print()
sample2=w.sample(n=4,random_state=2)
print(sample2)

   Distance  TimeToReach
2        20           25
9        55           70

4    0.05
1    0.05
5    0.10
0    0.05
dtype: float64


In [ ]:
#Question-2
# Specify the sample size as a fraction of the population size: 
# Example python program that samples, a DataFrame specifying the sample, size as a proportion to the DataFrame size, 
# We will be using FiveThirtyEight Comic Characters Dataset from Kaggle.

Download dataset: https://www.kaggle.com/datasets/fivethirtyeight/fivethirtyeight-comic-characters-dataset

In [48]:
import pandas as pd
data=pd.read_csv('marvel-wikia-data.csv')
sample=data.sample(frac=0.05)
sample  #print(sample)

page_id                           name  \
15805   425899             Blaast (Earth-616)   
3180     58659     Ralph Hutchins (Earth-616)   
2369    554007      Ted Mankowski (Earth-616)   
2996     34170      Hideko Takata (Earth-616)   
9475    555944    Maggie Langella (Earth-616)   
...        ...                            ...   
15232   695333  Mr. Taylor (Nova) (Earth-616)   
13480    29935              Visog (Earth-616)   
12656   346679            Myrrhot (Earth-616)   
4605     18848        Lydia Hardy (Earth-616)   
10657   453249       Doctor Grimm (Earth-616)   

                               urlslug                ID            ALIGN  \
15805             \/Blaast_(Earth-616)  No Dual Identity  Good Characters   
3180      \/Ralph_Hutchins_(Earth-616)   Secret Identity              NaN   
2369       \/Ted_Mankowski_(Earth-616)  No Dual Identity              NaN   
2996       \/Hideko_Takata_(Earth-616)   Public Identity              NaN   
9475     \/Maggie_Langella_(Earth-616)   Secret Identity   Bad Characters   
...                                ...               ...              ...   
15232  \/Mr._Taylor_(Nova)_(Earth-616)               NaN  Good Characters   
13480              \/Visog_(Earth-616)               NaN              NaN   
12656            \/Myrrhot_(Earth-616)   Public Identity   Bad Characters   
4605         \/Lydia_Hardy_(Earth-616)               NaN              NaN   
10657       \/Doctor_Grimm_(Earth-616)   Public Identity   Bad Characters   

              EYE        HAIR                SEX  GSM                ALIVE  \
15805         NaN     No Hair    Male Characters  NaN    Living Characters   
3180          NaN  Brown Hair    Male Characters  NaN    Living Characters   
2369          NaN         NaN    Male Characters  NaN    Living Characters   
2996          NaN  Black Hair  Female Characters  NaN    Living Characters   
9475          NaN         NaN  Female Characters  NaN    Living Characters   
...           ...         ...                ...  ...                  ...   
15232  Brown Eyes  Black Hair    Male Characters  NaN    Living Characters   
13480         NaN  Black Hair    Male Characters  NaN  Deceased Characters   
12656         NaN  Black Hair    Male Characters  NaN  Deceased Characters   
4605          NaN   Grey Hair  Female Characters  NaN    Living Characters   
10657         NaN        Bald    Male Characters  NaN  Deceased Characters   

       APPEARANCES FIRST APPEARANCE    Year  
15805          NaN           May-95  1995.0  
3180          10.0           Jul-80  1980.0  
2369          15.0           Oct-04  2004.0  
2996          11.0           Mar-86  1986.0  
9475           2.0           Mar-93  1993.0  
...            ...              ...     ...  
15232          1.0              NaN     NaN  
13480          1.0           Jun-94  1994.0  
12656          1.0           Dec-86  1986.0  
4605           6.0           Aug-79  1979.0  
10657          1.0           Jun-41  1941.0  

[819 rows x 13 columns]

In [ ]:
#Question-3
# Create a random sample from a pandas dataframe, code to create a dataframe is mentioned below.
# Complete it by randomly taking out 5 rows from a dataframe.
    
# Example Python program that creates a random sample from a pandas DataFrame  
# import pandas as pds
# Age vs call duration
# callTimes = {"Age": [20,25,31,37,43,44,52,58,64,68,70,77,82,86,91,96],
#              "Call Duration":[17,25,10,15,5,7,15,25,30,35,10,15,12,14,20,12]};
# dataFrame = pds.DataFrame(data=callTimes);

In [50]:
import pandas as pd
callTimes={'Age':[20,25,31,37,43,44,52,58,64,68,70,77,82,86,91,96],
            "Call Duration":[17,25,10,15,5,7,15,25,30,35,10,15,12,14,20,12]}
dataframe=pd.DataFrame(data=callTimes)
sample=dataframe.sample(n=5,random_state=1)
sample  #print(sample)

Age  Call Duration
3    37             15
13   86             14
7    58             25
2    31             10
6    52             15

In [ ]:
#Question-4
# Write a code to do systematic sampling, choosing every 10th element.
# Systematic Sampling definition
# Systematic sampling is a probability sampling method where elements from a target population are chosen by 
# selecting a random starting point and selecting sample members after a fixed ‘sampling interval.’ 
# This is implemented easily by selecting each ‘N’th element. Systematic sampling ensures that the full population
# is represented fairly.

In [43]:
import numpy as np
import pandas as pd
import random
number_of_house = 30
data = {'house_number': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,14, 15, 16, 17, 18, 19, 20, 21, 22, 23,24, 25, 26,
                         27, 28, 29, 30],
        'number_of_Adults': [2, 2, 5, 3, 2, 8, 4, 7, 8, 5, 4, 9, 5,4, 2, 3, 2, 3, 4, 5, 6, 4, 5, 4, 2, 6,2, 3, 2, 2]}
df = pd.DataFrame(data)
size_of_systematic_sample = 10
interval = (number_of_house // size_of_systematic_sample)
def systematic_sampling(df, step):
    indexes = np.arange(0, len(df), step=step)
    systematic_sample = df.iloc[indexes]
    return systematic_sample
systematic_sample = systematic_sampling(df, interval)
display(systematic_sample)
print()
systematic_data = round(systematic_sample['number_of_Adults'].mean())
print("Average Number Of Adults in Locality: ", systematic_data)

house_number  number_of_Adults
0              1                 2
3              4                 3
6              7                 4
9             10                 5
12            13                 5
15            16                 3
18            19                 4
21            22                 4
24            25                 2
27            28                 3


Average Number Of Adults in Locality:  4


In [ ]:
#Question-5
# Write a code to import the data in a data frame and take out 200 sample data 

Download dataset: https://www.kaggle.com/datasets/jb1433/sample-employees-monthly-salary

In [53]:
import pandas as pd
df=pd.read_csv('employees.csv')
sample=df.sample(n=200,random_state=10)
sample  #print(sample)

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
841       Ruby  Female   8/13/2006         6:27 PM   48354   19.501   
956    Beverly  Female  10/17/1986        12:51 AM   80838    8.115   
544      Roger    Male    7/3/2010         5:11 PM  105689   13.320   
173    Lillian  Female  12/21/2008         6:51 PM   85446    3.959   
759       Ruth  Female    9/2/1980         6:52 AM   59678   10.895   
..         ...     ...         ...             ...     ...      ...   
274     Howard    Male   10/5/1982         7:22 AM   97490    5.460   
192    Barbara     NaN    5/3/2003         7:32 PM   99326   16.475   
398      Doris  Female   7/29/1992         6:40 PM   85215    7.425   
450     Willie    Male   8/22/2009         1:03 PM   55038   19.691   
520      Peter    Male   2/22/2003         9:09 AM   56580    8.411   

    Senior Management                  Team  
841             False  Business Development  
956             False           Engineering  
544              True             Marketing  
173              True           Engineering  
759             False          Distribution  
..                ...                   ...  
274              True             Marketing  
192              True                 Legal  
398              True       Human Resources  
450             False                 Legal  
520              True                   NaN  

[200 rows x 8 columns]